### ISSUE TITLE
can't convert value of type (Response<[XMLRPCNode] .. . . . .. .

### ISSUE THREAD

**Issue by praveenislive** [kodlian/AlamofireXMLRPC#10]
![screen shot 2016-07-30 at 10 51 40 am](https://cloud.githubusercontent.com/assets/11039436/17268316/65c99496-5644-11e6-97d2-b254a60b61c5.png)

**Comment by kodlian** [comment]
The response should be `Response<XMLRPCNode, NSError>` not an array of `XMLRPCNode`

The readme is actually wrong, I will update it.
