### ISSUE TITLE
Optional(Error Domain=com.kodlian.XMLRPC.error Code=1 "Error Unknown" UserInfo={NSLocalizedFailureReason=Error Unknown})

### ISSUE THREAD

**Issue by praveenislive** [kodlian/AlamofireXMLRPC#13]
For one of my XMLRPC methods, I'm getting a really weird error:
Optional(Error Domain=com.kodlian.XMLRPC.error Code=1 "Error Unknown" UserInfo={NSLocalizedFailureReason=Error Unknown})

Any way to get anything more descriptive? What does this basically mean?

**Comment by kodlian** [comment]
It certainly due to a Fault response from the server. Please use a web proxy (like Charles Proxy) to capture the response of the server. In the latest version, you are now able to parse the Fault response.

**Comment by praveenislive** [comment]
https://www.flickr.com/services/api/request.xmlrpc.html
i want to use above flicker's demo service how i request in AlamofireXMLRPC ??

```
    let paramsDict:[String:String] = ["name":"value", "name2":"value2"];
    let params : [Any] = [paramsDict];
    AlamofireXMLRPC.request("https://api.flickr.com/services/xmlrpc/", methodName: "flickr.test.echo", parameters: params).responseXMLRPC { (response: Response<XMLRPCNode, XMLRPCError>) in

        print(response.result)
        print(response.result.value)

    }
```

i did like this and got failure result, what should i do , i spent 2-3 days on AlamofireXMLRPC but i didn't get response on many examples plz help me :'( i m crying . . :(

**Comment by kodlian** [comment]
Try with this, this will give you some clue about the issue. 

``` swift
let paramsDict: XMLRPCStructure = ["name":"value", "name2":"value2"]
let params: [Any] = [paramsDict]
AlamofireXMLRPC.request("https://api.flickr.com/services/xmlrpc/", methodName: "flickr.test.echo", parameters: params).responseXMLRPC { (response: Response<XMLRPCNode, XMLRPCError>) in
            if let error = response.result.error {
                switch error {
                case .Fault(node: let node):
                    print(node["faultString"].string)

                default:
                    print(error)
                }

            } else if let value = response.result.value {
                print(value)
            }
}
```

**Comment by Prince009** [comment]
Optional("Invalid API Key (Key has invalid format)")


i got this . .:(

**Comment by Prince009** [comment]
can i print the XMRPC Node in text format which i got from response??

**Comment by praveenislive** [comment]
Hey Jérémy,
Actually i am trying to get some data from odoo server and send request in xmlrpc format and get response in also xml node but i can't able to get the response :( 
here the oddo webservice url 
https://www.odoo.com/documentation/8.0/api_integration.html
plz help me on this thing . . . plz :'( 
otherwise i will be jobless :'(

**Comment by kodlian** [comment]
I can provide some helps on the usage of my framework but without specific codes and questions I can't help you at all.
To debug the XMLRPC call I recommend you to use a WebProxy like CharlesProxy in order to see the requests and responses.
Moreover It seems that the XMLRPC endpoints are not working in the demo instance .... (get a 301 or 404).

**Comment by Prince009** [comment]
Its a public chat i want to show my code which contain my userid and password .  .
can we chat in private environment??

**Comment by praveenislive** [comment]
okay just close it :(
