### ISSUE TITLE
AlamofireXMLRPC requests in a background fetch

### ISSUE THREAD

**Issue by SQEduard** [kodlian/AlamofireXMLRPC#18]
I'm trying to use AlamofireXMLRPC inside a background fetch.

My requests work fine if they're triggered while the app is active or it's state is changed to active, but when I trigger them inside a background fetch it seems like the execution stops as soon as the first request is being made.

If i then activate my app, the requests are processed as expected in the active state. If I activate the app too late i get a timeout error.

So is there any known issue with AlamofireXMLRPC regarding using it for background fetch?

**Comment by kodlian** [comment]
Not known to me. Underhood it's Alamofire that performs the request by using URLSession. You could try to perform a request directly on the same endpoint with Alamofire. You should probably take a look at the session manager: https://github.com/Alamofire/Alamofire#session-manager
