### ISSUE TITLE
Update for Xcode 9 and swift 4 ?

### ISSUE THREAD

**Issue by praveenislive** [kodlian/AlamofireXMLRPC#20]
@kodlian When will you update the lib for next version of ios?

**Comment by praveenislive** [comment]
Hi, @kodlian  will you please respond? I Need the lib in Xcode 9 with swift 4, I hope other audience who are using the lib they also want that, lib should be updated.

**Comment by tagallo** [comment]
Me too. Any ideas how to fix it?

**Comment by tagallo** [comment]
Using Xcode 9 with Swift 3.2 is also broken.

Swift Compiler Error:
`Type 'Int' does not conform to protocol 'XMLRPCRawValueRepresentable'`
`Type 'Int32' does not conform to protocol 'XMLRPCRawValueRepresentable'`
`Type 'Int8' does not conform to protocol 'XMLRPCRawValueRepresentable'`
`Type 'UInt16' does not conform to protocol 'XMLRPCRawValueRepresentable'`
`Type 'UInt8' does not conform to protocol 'XMLRPCRawValueRepresentable'`

**Comment by paulyhedral** [comment]
To be more precise, the compiler thinks that there are multiple exact matches of the initializer implementation. This is with Xcode 9 beta 6 with Swift 3.2.

```
/Volumes/Projects/Pilgrimage/Apps/Yawp/Pods/AlamofireXMLRPC/AlamofireXMLRPC/Value.swift:82:1: error: type 'Int' does not conform to protocol 'XMLRPCRawValueRepresentable'
extension Int: XMLRPCRawValueRepresentable {
^
/Volumes/Projects/Pilgrimage/Apps/Yawp/Pods/AlamofireXMLRPC/AlamofireXMLRPC/Value.swift:23:5: note: multiple matching initializers named 'init(xmlRpcRawValue:)' with type '(xmlRpcRawValue: String)'
    init?(xmlRpcRawValue: String)
    ^
/Volumes/Projects/Pilgrimage/Apps/Yawp/Pods/AlamofireXMLRPC/AlamofireXMLRPC/Value.swift:30:5: note: candidate exactly matches
    init?(xmlRpcRawValue: String) {
    ^
/Volumes/Projects/Pilgrimage/Apps/Yawp/Pods/AlamofireXMLRPC/AlamofireXMLRPC/Value.swift:70:12: note: candidate exactly matches
    public init?(xmlRpcRawValue: String) {
           ^
/Volumes/Projects/Pilgrimage/Apps/Yawp/Pods/AlamofireXMLRPC/AlamofireXMLRPC/Value.swift:93:12: note: candidate exactly matches
    public init?(xmlRpcRawValue: String) {
           ^
```

**Comment by sweetw0r** [comment]
Got same error for 'XMLRPCRawValueRepresentable'

**Comment by LordMochito** [comment]
I got the same error I Xcode 9, swift 3.2 and 4.

**Comment by filmhomage** [comment]
Got the same error Xcode 9 GM with Swift 3.2 and 4.

**Comment by andycheng123** [comment]
Same error Xcode 9 with swift 3.2 and 4

**Comment by filmhomage** [comment]
### Temporary solution

Comment out below lines;
https://github.com/filmhomage/AlamofireXMLRPC/blob/master/AlamofireXMLRPC/Value.swift#L75

```
// extension Int: StringRadixParsable { }
// extension Int32: StringRadixParsable { }
// extension Int8: StringRadixParsable { }
// extension UInt16: StringRadixParsable { }
// extension UInt8: StringRadixParsable { }
```

**Comment by kodlian** [comment]
Thanks all for your feedbacks, this should work now for swift 4 and Xcode9 👍

**Comment by filmhomage** [comment]
> Thanks all for your feedbacks, this should work now for swift 4 and Xcode9 👍

It works well! Thanks. 👍🏻

**Comment by andycheng123** [comment]
Thank you so much @kodlian
