### ISSUE TITLE
Error to use "authenticate" method. Error 2: parseFailed

### ISSUE THREAD

**Issue by augustocadini** [kodlian/AlamofireXMLRPC#25]
I'm using a Odoo service. When I trying log in, I receive the follow errror:

Auth Error
error The operation couldn’t be completed. (AlamofireXMLRPC.XMLRPCError error 2.)

Looking the error, of XMLRPCError. The error is: "parseFailed". But I don't know where I'am going wrong.

`AlamofireXMLRPC.request(self.host, methodName: "authenticate", parameters: paramsAuth).responseXMLRPC { (response: DataResponse<XMLRPCNode>) -> Void in
                switch response.result {
                case .success(let value):
                    print("Auth Success")
                    var str = String(data: response.data!, encoding: String.Encoding.utf8) as String!
                    print(str)
                    break
                case .failure(let error):
                    print("Auth Error")
                    print("error \(error.localizedDescription)")
                    break
                }`

The other methods of API odoo works fine: https://www.odoo.com/documentation/11.0/webservices/odoo.html.

**Comment by turganbekuly** [comment]
if you handled that problem, could you please give advice? @augustocadini
