### ISSUE TITLE
DownloadProgress totalUnitCount = -1

### ISSUE THREAD

**Issue by augustocadini** [kodlian/AlamofireXMLRPC#28]
I'm trying get download progress of a request but the variable `totalUnitCount` is -1.

```
       AlamofireXMLRPC.request(OdooAuth.host2!, methodName: "execute_kw", parameters: params).responseXMLRPC {
                (response: DataResponse<XMLRPCNode>) -> Void in          
                switch response.result {
                case .success(_ ):
                    break
                    
                case .failure(let err):
                break
            }.downloadProgress { (progress) in
                print("PROGRESS: \(Float(progress.completedUnitCount)) - \(Float(progress.totalUnitCount))")
        }
```

**OUTPUT*

> ...
> PROGRESS: 1012226.0 - -1.0
> PROGRESS: 1017048.0 - -1.0
> PROGRESS: 1128709.0 - -1.0
> PROGRESS: 1133445.0 - -1.0
> PROGRESS: 1242951.0 - -1.0
> PROGRESS: 1253212.0 - -1.0
> PROGRESS: 1354533.0 - -1.0
> PROGRESS: 1369654.0 - -1.0
> PROGRESS: 1397373.0 - -1.0
> PROGRESS: 1397760.0 - -1.0
> PROGRESS: 1467853.0 - -1.0
> PROGRESS: 1468243.0 - -1.0
> PROGRESS: 1538378.0 - -1.0
> ...

**Comment by kodlian** [comment]
This is something related to `Alamofire` directly. This is a request and not a download request. That mights explain the issue.
