### ISSUE TITLE
Problem with Iterate through Arrays

### ISSUE THREAD

**Issue by dastom** [kodlian/AlamofireXMLRPC#3]
If you iterate through the Arrays in a very big Response (in my case over 300 arrays you get after the second "child array" only 300 copies of one but not 300 different arrays.
Looks as if only the first one is simply copied 300 times.

This is the function i use:

```
func iterateNode(currentNode: [XMLRPCNode], durchgang: Int) {

    print("----- Anfang des Nodes: \(durchgang) -----")

    for everynode in currentNode {

        if let anzahl = everynode.count {
            print(anzahl)
        } else
        {
            print("keine Unterknoten zum zählen")
        }


        if let dict = everynode.dictionary {

            print("Anzahl der Einträge: \(dict.count)")


            for everdict in dict {
                let dictString = everdict.0

                if let value = everdict.1.string {
                    print("\(dictString): \(value)")

                }

            }


        }

        if everynode.count > 0 {
            let neueAnzahl = durchgang + 1
            print("--- Ende des Nodes: \(durchgang) ----")
            let testnode = everynode.array!
            self.iterateNode(testnode, durchgang: neueAnzahl)

        }
        else {

            print("--- Ende des Nodes ----")
        }

    }

} 
```

**Comment by kodlian** [comment]
Does the currentNode parameters you pass on your function come directly from the XMLRPC response?

Could you provide an example of XMLRPC response (not the 300 items but two elements should suffice)?

**Comment by dastom** [comment]
Hi,

first of all the response:

[response.txt](https://github.com/kodlian/AlamofireXMLRPC/files/53173/response.txt)

and thats the function with the request:

 func getData() -> [String] {

```
    var result = [String]()

    AlamofireXMLRPC.request("http://192.168.0.3:2001", methodName: "listDevices", parameters: nil).responseXMLRPC {
        (Response) in

        guard Response.result.isSuccess else {

            result.append("Fehler bei der Kommunikation")
            print("Fehler bei der Kommunikation")
            let fehler = Response.result.error
            print(fehler)

            return
        }

        print("Da scheinen Daten gekommen zu sein")
        let ergebnissNode = Response.result.value!

        self.iterateNode(ergebnissNode.array!, durchgang: 0)
    }

    return result

}
```

**Comment by dastom** [comment]
Any Idea ?

**Comment by kodlian** [comment]
The params is an array node that contains param(s). In your response you have an array in the first parameter where as in your code you make a foreach on the parameters node itself. You should first get the array contained in the first parameter.
The response - Params (array) with one Array that contains multiple nodes. VS your code - A Params node (Array) > that contains multiple nodes.
