### ISSUE TITLE
Update to Alamofire 5.0

### ISSUE THREAD

**Issue by jonathanfoster** [kodlian/AlamofireXMLRPC#33]
Alamofire 5.0 introduced a number of [breaking API changes](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%205.0%20Migration%20Guide.md) that make it incompatible with AlamofireXMLRPC. This mainly impacts `XMLResponseSerializer` and `XMLRPCResponseSerializer`.

In order to support the 5.0 API and maintain consistency, breaking changes must be introduced here. Serialization functions now throw instead of returning a result type.

I have a branch with the necessary changes. I'll submit a PR and see what everyone thinks.

**Comment by kodlian** [comment]
Closed as fixed in https://github.com/kodlian/AlamofireXMLRPC/pull/34 thanks!
